version: '3.6'

services:
  tdengine:
    image: beyouth/tdengine-server
    ports:
      - 6030:6030

  goclient:
    image: beyouth/tdengine-goclient
    volumes:
      - .:/app
    entrypoint: "sh /app/run-go.sh"

  pyclient:
    image: beyouth/tdengine-pyclient
    volumes:
      - .:/app
    entrypoint: "sh /app/run-py.sh"