FROM python:3.7.8-slim-stretch

ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib"
COPY inc/* /usr/include/
COPY driver/libtaos.so.1.6.6.1 /usr/lib/libtaos.so.1
COPY pip.conf /root/.pip/pip.conf
COPY python3 /build/

RUN cd /build/ && \
    python setup.py install && \
    echo "y" |cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    mkdir -p /etc/taos && \
    mkdir -p /data/log/ && \
    ln -s /usr/lib/libtaos.so.1 /usr/lib/libtaos.so

COPY taos.cfg /etc/taos

WORKDIR /app


