version: '3.6'

services:
  tdengine:
    image: beyouth/tdengine-server
    ports:
    - 6030:6030

  goclient:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
    entrypoint: "sh /app/run.sh"
